### ISSUE TITLE
Validator boolean fields present text inputs

### ISSUE THREAD

**Issue by dstockto** [zfcampus/zf-apigility-admin-ui#21]
This makes the value that is saved a string. Previous UI had a slider/toggle button.

![image](https://cloud.githubusercontent.com/assets/775393/6930547/7bd5c096-d7c1-11e4-83c3-faa8c2413fc4.png)

Typing in true or false will result in the string 'true' or the string 'false' being saved to the config.

**Comment by weierophinney** [comment]
@ezimuel This one is for you!

**Comment by ezimuel** [comment]
@dstockto This has been fixed with commit https://github.com/zfcampus/zf-apigility-admin-ui/commit/2695d17db02b51d624ca92bcd767bd98b446764f . Now we have a slider with on/off for boolean value:

![apigility-ui-boolean](https://cloud.githubusercontent.com/assets/475967/8282016/b45a4e92-18ed-11e5-8807-59f37b86cc34.png)
.

**Comment by dstockto** [comment]
Thank you @ezimuel
