### ISSUE TITLE
Add confirm checkbox label

### ISSUE THREAD

**Issue by ThaDafinser** [zfcampus/zf-apigility-admin-ui#88]
There are lot of confirm boxes like
```
<p><input type="checkbox" ng-disabled="vm.loading" ng-model="vm.recursive" class="ng-pristine ng-valid"> Delete all files and directories for this service</p>
```

Change it, that the labels are clickable
```
<p><label><input type="checkbox" ng-disabled="vm.loading" ng-model="vm.recursive" class="ng-pristine ng-valid"> Delete all files and directories for this service</label></p>
```

**Comment by gabrielsomoza** [comment]
bump :+1:

**Comment by colinkelly** [comment]
Yup, I agree that this will work for what you would like as a result. However, for sensitive actions as such, I would discourage making the check box easier than it is already. This is not an action that you should do everyday. Essentially, for a good API, the golden rule is: once a service is created, never remove it or change the results. This is why apigility has versioning into its core. Unless the API is for your own private use for an app or website.

It could add a better UX for certain applications of it. Though, for a confirmation checkbox to delete an API or a Service, I would disagree. It's not a good idea to make it easier and help ignorance destroy projects. Obviously, everyone should have backups.

**Comment by gabrielsomoza** [comment]
Good point about UX on very sensitive actions like deleting an API or services, although if that's really a concern a better way might be to take the approach where the user has to confirm by typing something on a text-box before being able to proceed.

For other cases (e.g. less sensitive settings on a service) I think its up to the person designing the API if they want to uncheck stuff on an endpoint's settings for example. The API might not yet be live, for example, and then the UI would be getting in the way rather than helping.

**Comment by ThaDafinser** [comment]
Dont use apigility currently and there seem to be concerns, although this a default behaviour users expect
