### ISSUE TITLE
erro on delete conect DB

### ISSUE THREAD

**Issue by blackhack123** [zfcampus/zf-apigility-admin-ui#96]
i have the nex error on delete the conect db service
on lcoal host 

![erro db](https://cloud.githubusercontent.com/assets/15680143/11872025/398d7212-a4a1-11e5-98bf-eb59e5049d37.JPG)

**Comment by colinkelly** [comment]
Is there a particular reason why you want a backslash in your db adapter name?

Looks like this issue could be solvable if you add a deprecated escape() function to the Delete and Update functions. However, on my environment which is the latest version of this code gives me the exact opposite. The adapter_name is escaped when saved and when I delete it, it does not escape the name(db-adapter/DB\colores converts into de-adapter/DB/colores) and can't delete. Although, by making a request to apigility/api/db-adapter/DB%5Ccolores does in fact delete the DB. I think that, by escaping %5C in the URL would delete correctly your adapter.

To start try any one of those URL by making a DELETE(using for example [Postman's](https://www.getpostman.com/) chrome app):
apigility/api/db-adapter/DB/colores
apigility/api/db-adapter/DB\colores
apigility/api/db-adapter/DB%255Ccolores  <-- escaped

This being said, I do not believe that you should be naming your adapter with a backslash. The "DB" at first is quite unnecessary because we are talking about an adapter. There is definitely a way to patch this issue in the UI. Although, I'm not sure if this is necessary.

Especially when working with APIs, it's not a good idea to mix names with a "\". There is probably a logic behind why you would wanna do that. I understand. However, there is probably another logical way of doing so.

Let me know about any results  ;)
